"""initial fresh migration

Revision ID: 2399656d3f62
Revises: 9ac8fe69aa9a
Create Date: 2025-11-30 21:58:02.515458

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2399656d3f62'
down_revision = '9ac8fe69aa9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('citizenship', sa.JSON(), nullable=True))
        batch_op.drop_column('citizenships')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('citizenships', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('citizenship')

    # ### end Alembic commands ###
