"""Create employees table

Revision ID: 63e88f6d3ee5
Revises: 8d6be5b70d6b
Create Date: 2025-11-07 17:36:19.711478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63e88f6d3ee5'
down_revision = '8d6be5b70d6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=100), nullable=False),
    sa.Column('lastName', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('personalEmail', sa.String(length=120), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('countryOfBirth', sa.String(length=100), nullable=True),
    sa.Column('citizenships', sa.JSON(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('employeeTitle', sa.String(length=100), nullable=True),
    sa.Column('departmentAdmin', sa.String(length=100), nullable=True),
    sa.Column('departmentAdvisor', sa.String(length=100), nullable=True),
    sa.Column('annualSalary', sa.Float(), nullable=True),
    sa.Column('visaType', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('filedBy', sa.String(length=100), nullable=True),
    sa.Column('caseType', sa.String(length=120), nullable=True),
    sa.Column('i94Number', sa.String(length=50), nullable=True),
    sa.Column('sevisId', sa.String(length=50), nullable=True),
    sa.Column('expirationDate', sa.Date(), nullable=True),
    sa.Column('visaStartDate', sa.Date(), nullable=True),
    sa.Column('initialH1BStartDate', sa.Date(), nullable=True),
    sa.Column('prepExtensionDate', sa.Date(), nullable=True),
    sa.Column('maxHPeriod', sa.Date(), nullable=True),
    sa.Column('i94ExpiryDate', sa.Date(), nullable=True),
    sa.Column('prFilingDate', sa.Date(), nullable=True),
    sa.Column('prStatus', sa.String(length=50), nullable=True),
    sa.Column('prNotes', sa.Text(), nullable=True),
    sa.Column('highestEducation', sa.String(length=50), nullable=True),
    sa.Column('fieldOfStudy', sa.String(length=100), nullable=True),
    sa.Column('socCode', sa.String(length=20), nullable=True),
    sa.Column('socCodeDescription', sa.String(length=200), nullable=True),
    sa.Column('generalNotes', sa.Text(), nullable=True),
    sa.Column('numberOfDependents', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    op.drop_table('admin')
    # ### end Alembic commands ###
