"""new database

Revision ID: 80839fe0f68c
Revises: 
Create Date: 2025-12-07 15:23:17.059828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '80839fe0f68c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('personal_email', sa.String(length=120), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('country_of_birth', sa.String(length=100), nullable=True),
    sa.Column('citizenship', sa.JSON(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('employee_title', sa.String(length=100), nullable=True),
    sa.Column('department_admin', sa.String(length=100), nullable=True),
    sa.Column('department_advisor', sa.String(length=100), nullable=True),
    sa.Column('annual_salary', sa.Float(), nullable=True),
    sa.Column('visa_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('filed_by', sa.String(length=100), nullable=True),
    sa.Column('case_type', sa.String(length=120), nullable=True),
    sa.Column('i94_number', sa.String(length=50), nullable=True),
    sa.Column('sevis_id', sa.String(length=50), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('visa_start_date', sa.Date(), nullable=True),
    sa.Column('initial_h1b_start_date', sa.Date(), nullable=True),
    sa.Column('prep_extension_date', sa.Date(), nullable=True),
    sa.Column('max_h_period', sa.Date(), nullable=True),
    sa.Column('i94_expiry_date', sa.Date(), nullable=True),
    sa.Column('pr_filing_date', sa.Date(), nullable=True),
    sa.Column('pr_status', sa.String(length=50), nullable=True),
    sa.Column('pr_notes', sa.Text(), nullable=True),
    sa.Column('highest_education', sa.String(length=50), nullable=True),
    sa.Column('field_of_study', sa.String(length=100), nullable=True),
    sa.Column('soc_code', sa.String(length=20), nullable=True),
    sa.Column('soc_code_description', sa.String(length=200), nullable=True),
    sa.Column('general_notes', sa.Text(), nullable=True),
    sa.Column('number_of_dependents', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('role', postgresql.ENUM('super_admin', 'admin', 'manager', 'viewer', name='userroleenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('visa_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('visa_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('added_by', sa.String(length=100), nullable=True),
    sa.Column('added_by_user_id', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visa_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visa_history_employee_id'), ['employee_id'], unique=False)

    op.create_table('visas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('prep_extension_date', sa.Date(), nullable=True),
    sa.Column('max_h_period', sa.Date(), nullable=True),
    sa.Column('document_expiry_i94', sa.Date(), nullable=True),
    sa.Column('permanent_residency_notes', sa.Text(), nullable=True),
    sa.Column('general_notes', sa.Text(), nullable=True),
    sa.Column('soc_code', sa.String(length=20), nullable=True),
    sa.Column('soc_description', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('employee_title', sa.String(length=120), nullable=True),
    sa.Column('admin', sa.String(length=120), nullable=True),
    sa.Column('advisor_pi_chair', sa.String(length=120), nullable=True),
    sa.Column('annual_salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('educational_level', sa.String(length=100), nullable=True),
    sa.Column('educational_field', sa.String(length=150), nullable=True),
    sa.Column('filed_by', sa.String(length=120), nullable=True),
    sa.Column('case_type', sa.String(length=80), nullable=True),
    sa.Column('status', postgresql.ENUM('valid', 'expired', 'pending', 'expiring_soon', name='visastatusenum'), server_default='valid', nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visas_employee_id'), ['employee_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visas_employee_id'))

    op.drop_table('visas')
    with op.batch_alter_table('visa_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visa_history_employee_id'))

    op.drop_table('visa_history')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('test')
    op.drop_table('employees')
    op.drop_table('admin')
    # ### end Alembic commands ###
