"""updated models

Revision ID: 9ac8fe69aa9a
Revises: fb969eb96eb7
Create Date: 2025-11-30 21:54:23.415929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ac8fe69aa9a'
down_revision = 'fb969eb96eb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_of_birth', sa.String(length=100), nullable=True))
        batch_op.drop_column('country')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('country_of_birth')

    # ### end Alembic commands ###
