"""initial fresh migration

Revision ID: acb0bd8f25e5
Revises: 2399656d3f62
Create Date: 2025-11-30 21:59:15.414305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acb0bd8f25e5'
down_revision = '2399656d3f62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_h1b_start', sa.Date(), nullable=True))
        batch_op.drop_column('initial_h1b_start')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initialH1BStartDate', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_column('initial_h1b_start')

    # ### end Alembic commands ###
