"""initial fresh migration

Revision ID: fb969eb96eb7
Revises: 
Create Date: 2025-11-30 21:47:18.741291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb969eb96eb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('personal_email', sa.String(length=120), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('citizenships', sa.JSON(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('employeeTitle', sa.String(length=100), nullable=True),
    sa.Column('departmentAdmin', sa.String(length=100), nullable=True),
    sa.Column('departmentAdvisor', sa.String(length=100), nullable=True),
    sa.Column('annualSalary', sa.Float(), nullable=True),
    sa.Column('visaType', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('filedBy', sa.String(length=100), nullable=True),
    sa.Column('caseType', sa.String(length=120), nullable=True),
    sa.Column('i94Number', sa.String(length=50), nullable=True),
    sa.Column('sevisId', sa.String(length=50), nullable=True),
    sa.Column('expirationDate', sa.Date(), nullable=True),
    sa.Column('visaStartDate', sa.Date(), nullable=True),
    sa.Column('initialH1BStartDate', sa.Date(), nullable=True),
    sa.Column('prepExtensionDate', sa.Date(), nullable=True),
    sa.Column('maxHPeriod', sa.Date(), nullable=True),
    sa.Column('i94ExpiryDate', sa.Date(), nullable=True),
    sa.Column('prFilingDate', sa.Date(), nullable=True),
    sa.Column('prStatus', sa.String(length=50), nullable=True),
    sa.Column('prNotes', sa.Text(), nullable=True),
    sa.Column('highestEducation', sa.String(length=50), nullable=True),
    sa.Column('fieldOfStudy', sa.String(length=100), nullable=True),
    sa.Column('socCode', sa.String(length=20), nullable=True),
    sa.Column('socCodeDescription', sa.String(length=200), nullable=True),
    sa.Column('generalNotes', sa.Text(), nullable=True),
    sa.Column('dependents', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('prep_extension_date', sa.Date(), nullable=True),
    sa.Column('max_h_period', sa.Date(), nullable=True),
    sa.Column('document_expiry_i94', sa.Date(), nullable=True),
    sa.Column('permanent_residency_notes', sa.Text(), nullable=True),
    sa.Column('general_notes', sa.Text(), nullable=True),
    sa.Column('soc_code', sa.String(length=20), nullable=True),
    sa.Column('soc_description', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('employee_title', sa.String(length=120), nullable=True),
    sa.Column('admin', sa.String(length=120), nullable=True),
    sa.Column('advisor_pi_chair', sa.String(length=120), nullable=True),
    sa.Column('annual_salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('educational_level', sa.String(length=100), nullable=True),
    sa.Column('educational_field', sa.String(length=150), nullable=True),
    sa.Column('filed_by', sa.String(length=120), nullable=True),
    sa.Column('case_type', sa.String(length=80), nullable=True),
    sa.Column('status', postgresql.ENUM('valid', 'expired', 'pending', 'expiring_soon', name='visastatusenum'), server_default='valid', nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visas_employee_id'), ['employee_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visas_employee_id'))

    op.drop_table('visas')
    op.drop_table('test')
    op.drop_table('employees')
    op.drop_table('admin')
    # ### end Alembic commands ###
